# Generated by Django 4.2.2 on 2023-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_alter_other_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={'ordering': ('-date', '-pk'), 'verbose_name_plural': 'Other'},
        ),
    ]
