# Generated by Django 4.2.2 on 2023-06-29 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 13, 37, 5, 870773), null=True),
        ),
    ]
