# Generated by Django 4.2.2 on 2023-06-29 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 13, 43, 58, 596133), null=True),
        ),
    ]
