# Generated by Django 4.2.2 on 2023-06-30 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 30, 15, 53, 53, 995901), null=True),
        ),
    ]
