# Generated by Django 4.2.2 on 2023-07-01 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 1, 7, 31, 6, 419122, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
