# Generated by Django 4.2.2 on 2023-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ('pk',), 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('pk',), 'verbose_name_plural': 'Photos'},
        ),
    ]
