# Generated by Django 4.2.2 on 2023-07-15 21:57

import django.core.validators
from django.db import migrations, models
import fullweb.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_appuser_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(6), fullweb.accounts.validators.letters_numbers_underscore_validator, fullweb.accounts.validators.maximum_two_underscores_validator]),
        ),
    ]
