# Generated by Django 4.2.2 on 2023-06-29 10:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 6, 29), max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MinLengthValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'pk'),
            },
        ),
    ]
