# Generated by Django 4.2.2 on 2023-06-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-date', '-pk')},
        ),
    ]
