# Generated by Django 4.2.2 on 2023-06-29 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 29), max_length=20, verbose_name='Income Date'),
        ),
    ]
