# Generated by Django 4.2.2 on 2023-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0013_alter_income_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-date', '-pk'), 'verbose_name_plural': 'Income'},
        ),
    ]
