# Generated by Django 4.2.2 on 2023-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_alter_daily_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ('-date', '-pk'), 'verbose_name_plural': 'Daily'},
        ),
    ]
