# Generated by Django 4.2.2 on 2023-07-01 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 9, 57, 34, 426965, tzinfo=datetime.timezone.utc), max_length=20),
        ),
    ]
